---
- name: Download repo.
  get_url:
    url: "{{ speedtest_yum_repo_url }}"
    dest: /etc/yum.repos.d/bintray-ookla-rhel.repo
    mode: '0644'
  when: speedtest_yum_repo_url | length

- name: Install speedtest.
  yum:
    name:
      - speedtest
    state: "{{ speedtest_package_state }}"
